name: Windows Tests Execution
on:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Type of tests to run'
        required: true
        default: 'integration'
#  pull_request:
#    types: [opened, reopened]
#    paths:
#      - '**.php'
#  push:
#    paths:
#      - '**.php'
jobs:
  php-tests:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    name: ${{ matrix.os }} - PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: win_tests

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=128M
          extensions: dom, curl, libxml, mbstring, zip, bcmath, intl
          coverage: none

      - name: Install composer
        run: composer install --no-interaction --prefer-dist

      - name: Execute tests on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo vendor/bin/phpunit

      - name: Execute tests on Windows
        if: matrix.os == 'windows-latest'
        run: vendor/bin/phpunit.bat